#!/bin/sh

#echo ">"
#echo "plantFEM >>  mode for Linux & OS X... "
#echo "Here, fortran script runs with  plantFEM-kernel."
#echo "You can debug your code with plantFEM-API"
#echo "  "
#echo "Initializing ..."

PF_HOME=$PWD

numcore=`cat /opt/plantfem/etc/cpucore`
exitc="exit"
man="man"
man1="man plantFEM"
man2="man plantFEM"
hostfile=""
keywords=""
cpucore="cpu-core"
install="install"
compress="compress"
mpif90="mpif90"
intel="intel"
debugMode="-"
ls="ls"
f90="f90"
run="run"
nano="nano"
vim="vim"
emacs="emacs"
code="code"
vi="vi"
cp="cp"
cd="cd"
ls="ls"
rm="rm"
grep="grep"
touch="touch"
pick="pick"
NAN=""
sendToDesktop=">>>"
ret=0
addonpath="addon"
init="init"
projectname=""
projectpath=""
num=""
remove="remove"

echo "If this is the first time, please type 'install' and press ENTER"
echo "Please input fortran script *.f90 | or check manual by 'man'  "
echo "  "
homepath="$PWD"
while :
do

    #echo "Please input fortran script *.f90 | or check manual by 'man'  "
    /bin/echo -n  ">>> "
    read commandl



    if [ "$commandl" = "use plantfem" ]; then
        echo "Interactive mode"
        echo "type 'end' after writing commands."
        echo "$commandl" > "__server__.f90"
        echo "implicit none" >> "__server__.f90"
        while :
        do
            /bin/echo -n ">>> "
            read line
            echo "$line" >> "__server__.f90"
            if [ "$line" = "end" ]; then
                #echo "end" >> "__server__.f90"
                $mpif90 -fopenmp -fopenacc /opt/plantfem/inc/*o -I /opt/plantfem/inc __server__.f90  -g -fcheck=all  -fintrinsic-modules-path /opt/plantfem/inc  -o  ./__server__.out
                mpirun   -np "$numcore"  ./__server__.out
                break
            fi
        done
        
        continue
    fi

    if [ "$commandl" = "again" ]; then
        mpirun   -np "$numcore" ./__server__.out
        continue
    fi
#    if [-d {"$commandl"} ]; then
#        # this is directory
#
#        $mpif90 /opt/plantfem/inc/*o "$1/server/server.f90" -g -fcheck=all  -fintrinsic-modules-path /opt/plantfem/inc/
#        #echo "Current num of cpu-core is :: $numcore "
#
#        #if [ "$hostfile" != "" ]; then
#        #    echo "hostfile is activated."
#        #    mpirun   --hostfile $hostfile -np $numcore ./server.out
#        #    continue
#        #fi
#        mpirun   -np $numcore ./server.out 
#        continue
#
#
#    fi 
    if [ "$commandl" = "tutorial" ]; then
        echo "===================================="
        echo "=====   Welcome to plantFEM   ======"
        echo "===================================="
        echo "Please type"
        echo " "
        echo "/opt/plantfem/plantfem search"
        echo " "
        echo "And press ENTER key"
        echo "Then, type a keyword."
        echo "===================================="
        continue
    fi
    
    if [ "$commandl" = "addon" ]; then
        echo "installing add-on"
        echo "Directory path of your awesome addon is : (default path = addon)"
        echo -n "> "
        read addonpath
        echo "installing from $addonpath"
        ls $addonpath | grep ".f90" > ap.txt
        sed -e 's/.f90//g' ap.txt > aps.txt
        cat aps.txt
        while read line
        do
            echo "Compiling /opt/plantfem/$addonpath/$line.f90      "
            echo " >> $line.o"
            echo " | ########################### | (100%)\r\c "
            mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all  -c /opt/plantfem/$addonpath/$line.f90 -o  /opt/plantfem/inc/$line.o
        done < /opt/plantfem/aps.txt
        echo " "
        rm ap.txt
        rm aps.txt
        continue
    fi

    if [ "$commandl" = "new" ]; then
        #echo "$homepath"
        echo "[Your project name:  (default=untitled), if OK, press ENTER]"
        /bin/echo -n ">>> "
        read projectname
        num=0
        if [ "x$projectname" = "x" ]; then
            pn="untitled"
        else
            pn="$projectname"
        fi
        echo "[Path of the project (default=$homepath/home/), if OK, press ENTER ]"
        /bin/echo -n ">>> "
        read projectpath
        if [ "x$projectpath" = "x" ]; then
            #$projectname="/opt/plantfem/home/"
            pan="$homepath/home/"
        else
            pan="$projectpath"
        fi
        echo "$pan$pn"

        mkdir -p $pan$pn
        echo "Which template do you want to use?"
        echo "1 : File-IO (std)"
        echo "2 : Linear solvers (std)"
        echo "3 ; MPI computing (std)"
        echo "4 : Array operation (std)"
        echo "5 : Create Mesh (fem)"
        echo "6 : Diffusion-1D simulation (sim)"
        echo "7 : Create soybean (obj)"
        echo "For more detail, please check /opt/plantfem/Tutorial/*"
        /bin/echo -n ">>> "
        read temp
        if [ "x$temp" = "x" ]; then
            cp /opt/plantfem/Tutorial/app/untitled.f90 server.f90
            echo "Note: a plain script is created. "
        elif [ "$temp" = "1" ]; then
            cp /opt/plantfem/Tutorial/playon_std/ex0002_fileIO.f90 server.f90
        elif [ "$temp" = "2" ]; then
            cp /opt/plantfem/Tutorial/playon_std/ex0007_easySolver.f90 server.f90
        elif [ "$temp" = "3" ]; then
            cp /opt/plantfem/Tutorial/playon_std/ex0005_mpi.f90  server.f90
        elif [ "$temp" = "4" ]; then
            cp /opt/plantfem/Tutorial/playon_std/ex0003_array.f90  server.f90
        elif [ "$temp" = "5" ]; then
            cp /opt/plantfem/Tutorial/playon_fem/ex0001_mesh.f90  server.f90
        elif [ "$temp" = "6" ]; then
            cp /opt/plantfem/Tutorial/playon_sim/ex0001_diffusion1D.f90 server.f90
        elif [ "$temp" = "7" ]; then
            cp /opt/plantfem/Tutorial/playon_obj/seed.f90 server.f90
        else
            cp /opt/plantfem/Tutorial/app/untitled.f90 server.f90
            echo "Caution: a plain script is created. "
        fi
        echo "New project is successfully created in here"
        echo " "
        echo "Check your script in"
        echo "./server.f90"
        echo " "
        echo "You can run the script by:"
        echo "plantfem run"
        echo " "
        continue
    fi


    if [ "$commandl" = "homepath" ]; then
        echo "$homepath"
        continue
    fi

    if [ "$commandl" = "clone" ]; then
        echo ">>> Please paste the remote repository URL."
        /bin/echo -n ">>> "
        read command 
        cd /opt/plantfem/addon/github/
        git clone "$command" 
        cd -
        continue
    fi

    if [ "$commandl" = "docker" ]; then
        sudo docker build github.com/kazulagi/plantfem
        sudo docker run --rm -it kazulagi/plantfem /bin/bash
        continue
    fi

    if [ "$commandl" = "update" ]; then
        sh /opt/plantfem/bin/update
        continue
    fi

    if [ "$commandl" = "search" ]; then
        echo "Type a keyword and press [ENTER]"
        read command
        echo "===================================="
        echo "These are examples"
        echo "===================================="
        grep -ril "$command" /opt/plantfem/Tutorial/*/*.f90
        echo "===================================="
        echo "Please type "
        echo "/opt/plantfem/plantfem load [Path to script with .f90 extention]"
        echo "And run by"
        echo "/opt/plantfem/plantfem run"
        continue
    fi

    if [ "$commandl" = "setup" ]; then
        python3 setup/setup.py
        sh /opt/plantfem/install/"$install"
        continue
    fi

    if [ "$commandl" = "load" ]; then
        echo "These are executable .f90 scripts."
        echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>"
        ls *.f90
        echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>"
        echo "Type your .f90 script name and press [ENTER]"
        read line
        cp "$line" ./server.f90
        echo "copied $2 to ./server.f90"
        continue
    fi

    if [ "$commandl" = "goback" ]; then
        echo "Back to plantFEM/"
        cd $homepath
        ls
        continue
    fi


    if [ "$commandl" = "pick" ]; then
        echo "copy to plantFEM/"
        echo "Input file-name."
        read filename
        cp $filename $homepath
        continue
    fi


    if [ "$commandl" = "search" ]; then
        echo "A keyword"
        read keyword
        ls /opt/plantfem/Tutorial/*/*.f90 | grep -i $keyword
        continue
    fi

    if [ "$commandl" = "gb" ]; then
        echo "Back to plantFEM/"
        cd $homepath
        ls
        continue
    fi

    if [ "$commandl" = "exit" ]; then
        echo "bye"
        break 
    fi

    if [ "$commandl" = "$sendToDesktop" ]; then
        echo "only for WSL :: "
        echo "Input file-name to send it to Desktop"
        read keywords
        echo "Input user-name of Windows"
        read username
        ln -s /mnt/c/Users/$username /opt/plantfem/Home
        ln -s /mnt/c/Users/$username/Desktop /opt/plantfem/Desktop
        echo "cp $keywords /mnt/c/Users/$username/Desktop/"
        cp $keywords /mnt/c/Users/$username/Desktop/
        continue
    fi

    if [ "$commandl" = "$debugMode" ]; then
        echo "Debug Mode :: Please input keywords of re-compile modules."
        read keywords
        echo $(cat /opt/plantfem/install/install | grep $keywords | grep -m1 mpif90)
        $(cat /opt/plantfem/install/install | grep $keywords| grep -m1 mpif90)
        continue
    fi

    if [ "$commandl" = "$intel" ]; then
        mpifort="mpiifort"
        install="install_ifort"
        echo "Intel fortran will be used."
        continue
    fi

    if [ "$commandl" = "hostfile" ]; then
        echo "Filepath of hostfile is : "
        read hostfile
        echo "Current hostfile is : $hostfile"
        continue
    fi

    if [ "$commandl" = "gcc" ]; then
        mpifort="mpifort"
        install="install"
        echo "GCC fortran will be used."
        continue
    fi

    if [ "$commandl" = $exitc ]; then
        continue
    fi
    if [ "$commandl" = "$man" ]; then
        less "/opt/plantfem/.man_plantFEM"
        continue
    fi
    if [ "$commandl" = "$man1" ]; then
        less "/opt/plantfem/.man_plantFEM"
        continue
    fi
    if [ "$commandl" = "$man2" ]; then
        less "/opt/plantfem/.man_plantFEM"
        continue
    fi
    if [ "$commandl" = "install" ]; then
        python3 /opt/plantfem/install.py
        continue
    fi
    if [ "$commandl" = "$compress" ]; then
        /opt/plantfem/bin/compress
        continue
    fi
    if [ "$commandl" = "$init" ]; then
        /opt/plantfem/bin/init
        continue
    fi
    if [ "$command" = "$remove" ]; then
        /opt/plantfem/bin/compress
        continue
    fi


    if [ "$commandl" = "$run" ]; then
        python3 /opt/plantfem/bin/check_end.py
        plantfem build
        #$mpif90 /opt/plantfem/inc/*o -I /opt/plantfem/inc /opt/plantfem/server.f90 -fopenmp -fopenacc -g -fcheck=all  -fintrinsic-modules-path /opt/plantfem/inc/     
        #echo "Current num of cpu-core is :: $numcore "

        #while read line
        #do 
        #    echo "num of process :: "$line && break 
        #done < /opt/plantfem/etc/cpucore

        if [ "$hostfile" != "" ]; then
            echo "hostfile is activated."
            mpirun   --hostfile $hostfile -np $numcore ./server.out "$2"
            continue
        fi

        mpirun   --hostfile /opt/plantfem/etc/hostfile -np $line ./server.out  "$2"
        
        continue
    fi


    if [ "$commandl" = "build" ]; then
        python3 /opt/plantfem/bin/check_end.py
        #cp server.f90 /opt/plantfem/server.f90
        $mpif90 -fopenmp -fopenacc /opt/plantfem/inc/*o -I /opt/plantfem/inc server.f90  -g -fcheck=all  -fintrinsic-modules-path /opt/plantfem/inc/  -o server.out
        #echo "Current num of cpu-core is :: $numcore "
        
        continue
    fi

    if [ "$commandl" = "$ls" ]; then
        echo " "
        pwd
        echo " "
        ls
        echo " "
        continue
    fi
    if [ "$commandl" = "$cpucore" ]; then
        numcore=`cat  /opt/plantfem/etc/cpucore`
        echo "Current num of cpu-core is :: $numcore "
        echo "Please input num of cpu-core"
        read numcore
        echo $numcore > /opt/plantfem/etc/cpucore
        echo "Current num of cpu-core is :: $numcore "
        continue
    fi



    echo "Invalid command :: $commandl"
    echo "Check command by man"

done    