#! /bin/bash

if [ $# -eq 0 ]; then
    python3 $PF_HOME/bin/run.py
fi
if [ $# -eq 1 ]; then
    python3 $PF_HOME/bin/run.py -s "$1" 
fi
if [ $# -eq 2 ]; then
    python3 $PF_HOME/bin/run.py -s "$1" -f "$2" 
fi
if [ $# -eq 3 ]; then
    python3 $PF_HOME/bin/run.py -s "$1" "$2" "$3"
fi

source .pf_profile