#!/bin/sh -eu


echo "-----------------"
echo "    "
echo "    "
echo "Installing plantFEM (22.04)"
echo " --- only fem ---   "
echo "    "
echo "    "
echo "-----------------"

echo "Compiling ./src/MeshClass/MeshClass.f90 " 
echo " >> MeshClass.o "
echo " | ======>                     | (30%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/MeshClass/MeshClass.f90 -o  ./inc/MeshClass.o
echo "Compiling ./src/MaterialPropClass/MaterialPropClass.f90 " 
echo " >> MaterialPropClass.o "
echo " | =======>                    | (35%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/MaterialPropClass/MaterialPropClass.f90 -o  ./inc/MaterialPropClass.o
echo "Compiling ./src/ControlParameterClass/ControlParameterClass.f90" 
echo " >> ControlParameterClass.o "
echo " | ========>                   | (40%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/ControlParameterClass/ControlParameterClass.f90 -o  ./inc/ControlParameterClass.o
echo "Compiling ./src/BoundaryConditionClass/BoundaryConditionClass.f90" 
echo " >> BoundaryConditionClass.o "
echo " | =========>                  | (45%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/BoundaryConditionClass/BoundaryConditionClass.f90 -o  ./inc/BoundaryConditionClass.o
echo "Compiling ./src/StrainClass/StrainClass.f90" 
echo " >> StrainClass.o "
echo " | =============>              | (65%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/StrainClass/StrainClass.f90 -o  ./inc/StrainClass.o
echo "Compiling ./src/StressClass/StressClass.f90" 
echo " >> StressClass.o "
echo " | =============>              | (65%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/StressClass/StressClass.f90 -o  ./inc/StressClass.o
echo "Compiling ./src/ConstitutiveModelClass/ConstitutiveModelClass.f90" 
echo " >> ConstitutiveModelClass.o"
echo " | =============>              | (65%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/ConstitutiveModelClass/ConstitutiveModelClass.f90 -o  ./inc/ConstitutiveModelClass.o
# Compilation of high-level classes

echo "Compiling ./src/FEMDomainClass/FEMDomainClass.f90 " 
echo " >> FEMDomainClass.o  " 
echo " | =============>              | (65%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/FEMDomainClass/FEMDomainClass.f90 -o  ./inc/FEMDomainClass.o 
echo "Compiling ./src/FEMSolverClass/FEMSolverClass.f90 " 
echo " >> FEMSolverClass.o  " 
echo " | =============>              | (65%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/FEMSolverClass/FEMSolverClass.f90 -o  ./inc/FEMSolverClass.o 


echo "Compiling ./src/FEMIfaceClass/FEMIfaceClass.f90" 
echo " >> FEMIfaceClass.o "
echo " | ==============>             | (66%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/FEMIfaceClass/FEMIfaceClass.f90 -o  ./inc/FEMIfaceClass.o
echo "Compiling ./src/PostProcessingClass/PostProcessingClass.f90" 
echo " >> PostProcessingClass.o "
echo " | ===============>            | (66%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PostProcessingClass/PostProcessingClass.f90 -o  ./inc/PostProcessingClass.o
echo "Compiling ./src/PreProcessingClass/PreProcessingClass.f90" 
echo " >> PreProcessingClass.o "
echo " | ===============>            | (67%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PreProcessingClass/PreProcessingClass.f90 -o  ./inc/PreProcessingClass.o
echo "Compiling ./src/fem/fem.f90" 
echo " >> fem.o "
echo " | ===============>            | (68%)\r\c"
mpif90 -fopenmp -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/fem/fem.f90 -o  ./inc/fem.o
echo "Modules for FEM (fem) is installed.       "

mv *.mod inc/

echo " [plantFEM/fem] is successfully installed !!"
echo "    "