#!/bin/sh -eu

echo "-----------------"
echo "    "
echo "    "
echo "Installing plantFEM (21.10)"
echo "    "
echo "    "
echo "-----------------"

if [ "$1" = "std" ]; then
    sh "install/install_std"
elif [ "$1" = "fem" ]; then
    sh "install/install_fem"
elif [ "$1" = "sim" ]; then
    sh "install/install_sim"
elif [ "$1" = "obj" ]; then
    sh "install/install_obj"
else
    sh "install/install_std"
    sh "install/install_fem"
    sh "install/install_sim"
    sh "install/install_obj"
fi

echo " plantFEM is successfully installed !!"
echo "    "