#!/bin/sh -eu

echo "-----------------"
echo "    "
echo "    "
echo "SiCroF is installing ..."
echo "(c) Haruka Tomobe 2019 All Rights Reserved"
echo "    "
echo "    "
echo "-----------------"

#echo "Pre-install sequence is started... "
#echo "Skip it  y/n ? :"
#read yes_no
#yes="y"
#if [ $yes_no != $yes ]; then
#echo "------------------------"
#echo "gcc --version"
#gcc --version
#echo "------------------------"
#echo "gfortran --version"
#gfortran --version
#echo "------------------------"
#echo "gmsh --version"
#gmsh --version
#echo "------------------------"
#echo  -shared -fPIC"mpif90 -g -fcheck=all  --version"
#mpif9 -shared -fPIC0 -g -fcheck=all  --version
#echo "------------------------"
##echo "OpenCL --version"
##clinfo --version
##sudo apt install ocl-icd-libopencl1 opencl-headers clinfo ocl-icd-opencl-dev beignet
#echo "------------------------"
#echo "python3 --version"
#python3 --version
#echo "------------------------"
#echo "pip3 --version"
#pip3 --version
#echo "------------------------"
#pip3 install pillow
#echo "------------------------"
#pip3 install numpy
#echo "------------------------"
#pip3 install scipy
#echo "------------------------"
#pip3 install matplotlib
#echo "------------------------"
#pip3 install tensorflow
#echo "------------------------"
#pip3 install jupyter
#echo "------------------------"
#
#echo "All pacages are ready. [ok]"
## Compilation of low-level classes
#fi


start_time=`date +%s%3N`

echo "Compiling ./src/TermClass/TermClass.f90      "
echo " >> TermClass.o"
echo " |                             | (0%)\r\c "
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/TermClass/TermClass.f90 -o  ./inc/TermClass.o
echo "Compiling ./src/MathClass/MathClass.f90   "
echo " >> MathClass.o"
echo " | #                           | (2%)\r\c "
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/MathClass/MathClass.f90 -o  ./inc/MathClass.o
echo "Compiling ./src/KinematicClass/KinematicClass.f90   "
echo " >> KinematicClass.o"
echo " | #                           | (2%)\r\c "
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/KinematicClass/KinematicClass.f90 -o  ./inc/KinematicClass.o
echo "Compiling ./src/RandomClass/RandomClass.f90   "
echo " >> RandomClass.o"
echo " | #                           | (2%)\r\c "
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/RandomClass/RandomClass.f90 -o  ./inc/RandomClass.o
echo "Compiling ./src/ArrayClass/ArrayClass.f90 " 
echo " >> ArrayClass.o "
echo " | #                           | (4%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/ArrayClass/ArrayClass.f90 -o  ./inc/ArrayClass.o
echo "Compiling ./src/VectorClass/VectorClass.f90 " 
echo " >> VectorClass.o "
echo " | #                           | (4%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/VectorClass/VectorClass.f90 -o  ./inc/Vector.o
echo "Compiling ./src/EquationClass/EquationClass.f90 " 
echo " >> EquationClass.o "
echo " | #                           | (4%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/EquationClass/EquationClass.f90 -o  ./inc/Equation.o
echo "Compiling ./src/MPIClass/MPIClass.f90       "
echo " >> MPIClass.o"
echo " | #                           | (5%)\r\c "
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/MPIClass/MPIClass.f90 -o  ./inc/MPIClass.o
echo "Compiling ./src/DictionaryClass/DictionaryClass.f90      "
echo " >> DictionaryClass.o"
echo " | ##                          | (9%)\r\c "
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/DictionaryClass/DictionaryClass.f90 -o  ./inc/DictionaryClass.o
echo "Compiling ./src/OpenMPClass/OpenMPClass.f90 "
echo " >> OpenMPClass.o"
echo " | ###                         | (12%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/OpenMPClass/OpenMPClass.f90 -o  ./inc/OpenMPClass.o
echo "Compiling ./src/LinearSolverClass/LinearSolverClass.f90 " 
echo " >> LinearSolverClass.o "
echo " | ####                        | (16%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/LinearSolverClass/LinearSolverClass.f90 -o  ./inc/LinearSolverClass.o
echo "Compiling ./src/GeometryClass/GeometryClass.f90 " 
echo " >> GeometryClass.o "
echo " | #####                       | (22%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/GeometryClass/GeometryClass.f90 -o  ./inc/GeometryClass.o
echo "Compiling ./src/RouteOptimizationClass/RouteOptimizationClass.f90 " 
echo " >> RouteOptimizationClass.o "
echo " | #####                       | (22%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/RouteOptimizationClass/RouteOptimizationClass.f90 -o  ./inc/RouteOptimizationClass.o
echo "Compiling ./src/TreeClass/TreeClass.f90 "
echo " >> TreeClass.o"
echo " | ######                      | (24%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/TreeClass/TreeClass.f90 -o  ./inc/TreeClass.o
echo "Compiling ./src/ShapeFunctionClass/ShapeFunctionClass.f90 " 
echo " >> ShapeFunctionClass.o "
echo " | ######                      | (26%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/ShapeFunctionClass/ShapeFunctionClass.f90 -o  ./inc/ShapeFunctionClass.o
echo "Compiling ./src/std/std.f90 " 
echo " >> std.o "
echo " | #######                     | (30%)\r\c"
echo "Standard library (std) is compiled."
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/std/std.f90 -o  ./inc/std.o
echo "Compiling ./src/MeshClass/MeshClass.f90 " 
echo " >> MeshClass.o "
echo " | #######                     | (30%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/MeshClass/MeshClass.f90 -o  ./inc/MeshClass.o
echo "Compiling ./src/MaterialPropClass/MaterialPropClass.f90 " 
echo " >> MaterialPropClass.o "
echo " | ########                    | (35%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/MaterialPropClass/MaterialPropClass.f90 -o  ./inc/MaterialPropClass.o
echo "Compiling ./src/ControlParameterClass/ControlParameterClass.f90" 
echo " >> ControlParameterClass.o "
echo " | #########                   | (40%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/ControlParameterClass/ControlParameterClass.f90 -o  ./inc/ControlParameterClass.o
echo "Compiling ./src/BoundaryConditionClass/BoundaryConditionClass.f90" 
echo " >> BoundaryConditionClass.o "
echo " | ##########                  | (45%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/BoundaryConditionClass/BoundaryConditionClass.f90 -o  ./inc/BoundaryConditionClass.o
echo "Compiling ./src/StrainClass/StrainClass.f90" 
echo " >> StrainClass.o "
echo " | ##############              | (65%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/StrainClass/StrainClass.f90 -o  ./inc/StrainClass.o
echo "Compiling ./src/StressClass/StressClass.f90" 
echo " >> StressClass.o "
echo " | ##############              | (65%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/StressClass/StressClass.f90 -o  ./inc/StressClass.o
echo "Compiling ./src/ConstitutiveModelClass/ConstitutiveModelClass.f90" 
echo " >> ConstitutiveModelClass.o"
echo " | ###########                 | (50%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/ConstitutiveModelClass/ConstitutiveModelClass.f90 -o  ./inc/ConstitutiveModelClass.o
# Compilation of high-level classes
echo "Compiling ./src/FEMDomainClass/FEMDomainClass.f90 " 
echo " >> FEMDomainClass.o  " 
echo " | ############                | (55%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/FEMDomainClass/FEMDomainClass.f90 -o  ./inc/FEMDomainClass.o 
echo "Compiling ./src/FEMIfaceClass/FEMIfaceClass.f90" 
echo " >> FEMIfaceClass.o "
echo " | #############               | (60%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/FEMIfaceClass/FEMIfaceClass.f90 -o  ./inc/FEMIfaceClass.o
echo "Compiling ./src/PostProcessingClass/PostProcessingClass.f90" 
echo " >> PostProcessingClass.o "
echo " | ##############              | (63%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/PostProcessingClass/PostProcessingClass.f90 -o  ./inc/PostProcessingClass.o
echo "Compiling ./src/PreProcessingClass/PreProcessingClass.f90" 
echo " >> PreProcessingClass.o "
echo " | ##############              | (65%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/PreProcessingClass/PreProcessingClass.f90 -o  ./inc/PreProcessingClass.o
echo "Compiling ./src/fem/fem.f90" 
echo " >> fem.o "
echo " | ##############              | (65%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/fem/fem.f90 -o  ./inc/fem.o
echo "Modules for FEM (fem) is installed."



# Compilation of Solvers
echo "Compiling ./src/DiffusionEquationClass/DiffusionEquationClass.f90" 
echo " >> DiffusionEquationClass.o "
echo " | ###############             | (70%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/DiffusionEquationClass/DiffusionEquationClass.f90 -o  ./inc/DiffusionEquationClass.o
echo "Compiling ./src/FiniteDeformationClass/FiniteDeformationClass.f90" 
echo " >> FiniteDeformationClass.o "
echo " | ################            | (75%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/FiniteDeformationClass/FiniteDeformationClass.f90 -o  ./inc/FiniteDeformationClass.o
echo "Compiling ./src/ContactMechanicsClass/ContactMechanicsClass.f90" 
echo " >> ContactMechanicsClass.o "
echo " | #################           | (80%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/ContactMechanicsClass/ContactMechanicsClass.f90 -o  ./inc/ContactMechanicsClass.o
echo "Compiling ./src/MultiDiffDeformClass/MultiDiffDeformClass.f90" 
echo " >> MultiDiffDeformClass.o "
echo " | ####################        | (85%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/MultiDiffDeformClass/MultiDiffDeformClass.f90 -o  ./inc/MultiDiffDeformClass.o
echo "Compiling ./src/MultiPhysicsClass/MultiPhysicsClass.f90" 
echo " >> MultiPhysicsClass.o "
echo " | ####################        | (85%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/MultiPhysicsClass/MultiPhysicsClass.f90 -o  ./inc/MultiPhysicsClass.o
echo "Compiling ./src/SpaceTimeDeformClass/SpaceTimeDeformClass.f90" 
echo " >> SpaceTimeDeformClass.o "
echo " | ####################        | (85%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/SpaceTimeDeformClass/SpaceTimeDeformClass.f90 -o  ./inc/SpaceTimeDeformClass.o
echo "Compiling ./src/WaterAbsorptionClass/WaterAbsorptionClass.f90" 
echo " >> WaterAbsorptionClass.o "
echo " | ####################        | (85%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/WaterAbsorptionClass/WaterAbsorptionClass.f90 -o  ./inc/WaterAbsorptionClass.o
# Compilation of Fields 
echo "Compiling ./src/FieldClass/FieldClass.f90" 
echo " >> FieldClass.o"
echo " | ####################        | (87%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/FieldClass/FieldClass.f90 -o  ./inc/FieldClass.o
echo "Compiling ./src/SimulatorClass/SimulatorClass.f90" 
echo " >> SimulatorClass.o"
echo " | ####################        | (87%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/SimulatorClass/SimulatorClass.f90 -o  ./inc/SimulatorClass.o
echo "Compiling ./src/SiCroFClass/SiCroFClass.f90" 
echo " >> SiCroFClass.o"
echo " | ####################        | (87%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/SiCroFClass/SiCroFClass.f90 -o  ./inc/SiCroFClass.o
echo "Compiling ./src/sim/sim.f90" 
echo " >> sim.o "
echo " | ##############              | (65%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/sim/sim.f90 -o  ./inc/sim.o
echo "Modules for simulators (sim) is installed."


# Compilation of agricultural objects
echo "Compiling ./src/StemClass/StemClass.f90" 
echo " >> StemClass.o "
echo " | ########################    | (90%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/StemClass/StemClass.f90 -o  ./inc/StemClass.o
echo "Compiling ./src/PlantRootClass/PlantRootClass.f90" 
echo " >> PlantRootClass.o "
echo " | ########################    | (90%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/PlantRootClass/PlantRootClass.f90 -o  ./inc/PlantRootClass.o
echo "Compiling ./src/PetiClass/PetiClass.f90" 
echo " >> PetiClass.o "
echo " | ########################    | (90%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/PetiClass/PetiClass.f90 -o  ./inc/PetiClass.o
echo "Compiling ./src/PodClass/PodClass.f90" 
echo " >> PodClass.o "
echo " | ########################    | (90%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/PodClass/PodClass.f90 -o  ./inc/PodClass.o
echo "Compiling ./src/FlowerClass/FlowerClass.f90" 
echo " >> FlowerClass.o "
echo " | ########################    | (92%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/FlowerClass/FlowerClass.f90 -o  ./inc/FlowerClass.o
echo "Compiling ./src/PanicleClass/PanicleClass.f90" 
echo " >> PanicleClass.o "
echo " | ########################    | (92%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/PanicleClass/PanicleClass.f90 -o  ./inc/PanicleClass.o
echo "Compiling ./src/LeafClass/LeafClass.f90" 
echo " >> LeafClass.o "
echo " | ########################    | (92%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/LeafClass/LeafClass.f90 -o  ./inc/LeafClass.o
echo "Compiling ./src/PlantNodeClass/PlantNodeClass.f90" 
echo " >> PlantNodeClass.o "
echo " | ########################    | (92%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/PlantNodeClass/PlantNodeClass.f90 -o  ./inc/PlantNodeClass.o
echo "Compiling ./src/LsystemClass/LsystemClass.f90" 
echo " >> LsystemClass.o "
echo " | ##########################  | (95%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/LsystemClass/LsystemClass.f90 -o  ./inc/LsystemClass.o
echo "Compiling ./src/SeedClass/SeedClass.f90" 
echo " >> SeedClass.o "
echo " | ##########################  | (95%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/SeedClass/SeedClass.f90 -o  ./inc/SeedClass.o
echo "Compiling ./src/SoilClass/SoilClass.f90" 
echo " >> SoilClass.o "
echo " | ########################## |  (99%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/SoilClass/SoilClass.f90 -o  ./inc/SoilClass.o
echo "Compiling ./src/SoybeanClass/SoybeanClass.f90" 
echo " >> SoybeanClass.o "
echo " | ########################## |  (99%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/SoybeanClass/SoybeanClass.f90 -o  ./inc/SoybeanClass.o
echo "Compiling ./src/FarmClass/FarmClass.f90" 
echo " >> FarmClass.o "
echo " | ########################## |  (99%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/FarmClass/FarmClass.f90 -o  ./inc/FarmClass.o
echo "Compiling ./src/obj/obj.f90" 
echo " >> obj.o "
echo " | ########################## |  (99%)\r\c"
mpif90 -shared -fPIC -g -fcheck=all  -c ./src/obj/obj.f90 -o  ./inc/obj.o
echo "Modules for field-objects (obj) is installed."
mpif90 -shared -fPIC -g -fcheck=all  -o obj.so ./inc/*.o 

echo "Copying input files from INPUT/           " 
echo " >> *.txt, *.scf"
echo " | ########################### | (100%)\r"
cp ipynb/* .
echo "    "

echo "#!/bin/sh" > sicrof
echo "cd /home/haruka/SiCroF" >> sicrof
echo "python3 SiCroF.py" >> sicrof

end_time=`date +%s%3N`
time=$((end_time - start_time)) 
NANOTIME=`echo "scale=3; ($time)/1000" | bc`
echo " Total 22 objects are compiled in "${NANOTIME}" sec. "
echo " SiCroF is successfully installed !!"
echo "    "
