#!/bin/sh -eu

echo "-----------------"
echo "    "
echo "    "
echo "SiCroF is installing ..."
echo "(c) Haruka Tomobe 2019 All Rights Reserved"
echo "    "
echo "    "
echo "-----------------"

#echo "Pre-install sequence is started... "
#echo "Skip it  y/n ? :"
#read yes_no
#yes="y"
#if [ $yes_no != $yes ]; then
#echo "------------------------"
#echo "gcc --version"
#gcc --version
#brew install gcc
#echo "------------------------"
#echo "gfortran --version"
#gfortran --version
#echo "------------------------"
#echo "gmsh --version"
#gmsh --version
#brew install gmsh
#echo "------------------------"
#echo "mpifort --version"
#mpifort --version
#brew install openmpi
#echo "------------------------"
#echo "OpenCL --version"
#clinfo --version
#brew install clinfo
#echo "------------------------"
#echo "python3 --version"
#python3 --version
#brew install python3
#echo "------------------------"
#echo "pip3 --version"
#pip3 --version
#brew install python3-pip
#echo "------------------------"
#pip3 install pillow
#echo "------------------------"
#pip3 install numpy
#echo "------------------------"
#pip3 install scipy
#echo "------------------------"
#pip3 install matplotlib
#echo "------------------------"
#pip3 install tensorflow
#echo "------------------------"
#
#echo "All pacages are ready. [ok]"
## Compilation of low-level classes
#fi

rm ./inc/*.o


echo "Compiling ./src/TermClass/TermClass.f90      "
echo " >> TermClass.o"
echo " |                             | (0%)\r\c "
mpifort -c ./src/TermClass/TermClass.f90 -o  ./inc/TermClass.o
echo "Compiling ./src/MathClass/MathClass.f90   "
echo " >> MathClass.o"
echo " | #                           | (2%)\r\c "
mpifort -c ./src/MathClass/MathClass.f90 -o  ./inc/MathClass.o
echo "Compiling ./src/RandomClass/RandomClass.f90   "
echo " >> RandomClass.o"
echo " | #                           | (2%)\r\c "
mpifort -c ./src/RandomClass/RandomClass.f90 -o  ./inc/RandomClass.o
echo "Compiling ./src/MPIClass/MPIClass.f90       "
echo " >> MPIClass.o"
echo " | #                           | (5%)\r\c "
mpifort -c ./src/MPIClass/MPIClass.f90 -o  ./inc/MPIClass.o
echo "Compiling ./src/DictionaryClass/DictionaryClass.f90      "
echo " >> DictionaryClass.o"
echo " | ##                          | (9%)\r\c "
mpifort -c ./src/DictionaryClass/DictionaryClass.f90 -o  ./inc/DictionaryClass.o
echo "Compiling ./src/OpenMPClass/OpenMPClass.f90 "
echo " >> OpenMPClass.o"
echo " | ###                         | (12%)\r\c"
mpifort -c ./src/OpenMPClass/OpenMPClass.f90 -o  ./inc/OpenMPClass.o
echo "Compiling ./src/LinearSolverClass/LinearSolverClass.f90 " 
echo " >> LinearSolverClass.o "
echo " | ####                        | (16%)\r\c"
mpifort -c ./src/LinearSolverClass/LinearSolverClass.f90 -o  ./inc/LinearSolverClass.o
echo "Compiling ./src/ArrayOperationClass/ArrayOperationClass.f90 " 
echo " >> ArrayOperationClass.o "
echo " | #####                       | (20%)\r\c"
mpifort -c ./src/ArrayOperationClass/ArrayOperationClass.f90 -o  ./inc/ArrayOperationClass.o
echo "Compiling ./src/GeometryClass/GeometryClass.f90 " 
echo " >> GeometryClass.o "
echo " | #####                       | (22%)\r\c"
mpifort -c ./src/GeometryClass/GeometryClass.f90 -o  ./inc/GeometryClass.o
echo "Compiling ./src/TreeClass/TreeClass.f90 "
echo " >> TreeClass.o"
echo " | ######                      | (24%)\r\c"
mpifort -c ./src/TreeClass/TreeClass.f90 -o  ./inc/TreeClass.o
echo "Compiling ./src/ShapeFunctionClass/ShapeFunctionClass.f90 " 
echo " >> ShapeFunctionClass.o "
echo " | ######                      | (26%)\r\c"
mpifort -c ./src/ShapeFunctionClass/ShapeFunctionClass.f90 -o  ./inc/ShapeFunctionClass.o
echo "Compiling ./src/MeshOperationClass/MeshOperationClass.f90 " 
echo " >> MeshOperationClass.o "
echo " | #######                     | (30%)\r\c"
mpifort -c ./src/MeshOperationClass/MeshOperationClass.f90 -o  ./inc/MeshOperationClass.o
echo "Compiling ./src/MaterialPropClass/MaterialPropClass.f90 " 
echo " >> MaterialPropClass.o "
echo " | ########                    | (35%)\r\c"
mpifort -c ./src/MaterialPropClass/MaterialPropClass.f90 -o  ./inc/MaterialPropClass.o
echo "Compiling ./src/ControlParameterClass/ControlParameterClass.f90" 
echo " >> ControlParameterClass.o "
echo " | #########                   | (40%)\r\c"
mpifort -c ./src/ControlParameterClass/ControlParameterClass.f90 -o  ./inc/ControlParameterClass.o
echo "Compiling ./src/BoundaryConditionClass/BoundaryConditionClass.f90" 
echo " >> BoundaryConditionClass.o "
echo " | ##########                  | (45%)\r\c"
mpifort -c ./src/BoundaryConditionClass/BoundaryConditionClass.f90 -o  ./inc/BoundaryConditionClass.o

# Strain and stress measure
echo "Compiling ./src/StrainClass/StrainClass.f90" 
echo " >> StrainClass.o "
echo " | ##############              | (65%)\r\c"
mpifort -c ./src/StrainClass/StrainClass.f90 -o  ./inc/StrainClass.o
echo "Compiling ./src/StressClass/StressClass.f90" 
echo " >> StressClass.o "
echo " | ##############              | (65%)\r\c"
mpifort -c ./src/StressClass/StressClass.f90 -o  ./inc/StressClass.o
echo "Compiling ./src/ConstitutiveModelClass/ConstitutiveModelClass.f90" 
echo " >> ConstitutiveModelClass.o"
echo " | ###########                 | (50%)\r\c"
mpifort -c ./src/ConstitutiveModelClass/ConstitutiveModelClass.f90 -o  ./inc/ConstitutiveModelClass.o
# Compilation of high-level classes
echo "Compiling ./src/FEMDomainClass/FEMDomainClass.f90 " 
echo " >> FEMDomainClass.o  " 
echo " | ############                | (55%)\r\c"
mpifort -c ./src/FEMDomainClass/FEMDomainClass.f90 -o  ./inc/FEMDomainClass.o 
echo "Compiling ./src/FEMIfaceClass/FEMIfaceClass.f90" 
echo " >> FEMIfaceClass.o "
echo " | #############               | (60%)\r\c"
mpifort -c ./src/FEMIfaceClass/FEMIfaceClass.f90 -o  ./inc/FEMIfaceClass.o
echo "Compiling ./src/PostProcessingClass/PostProcessingClass.f90" 
echo " >> PostProcessingClass.o "
echo " | ##############              | (63%)\r\c"
mpifort -c ./src/PostProcessingClass/PostProcessingClass.f90 -o  ./inc/PostProcessingClass.o
echo "Compiling ./src/PreProcessingClass/PreProcessingClass.f90" 
echo " >> PreProcessingClass.o "
echo " | ##############              | (65%)\r\c"
mpifort -c ./src/PreProcessingClass/PreProcessingClass.f90 -o  ./inc/PreProcessingClass.o
echo "Compiling ./src/LsystemClass/LsystemClass.f90" 
echo " >> LsystemClass.o "
echo " | ##############              | (65%)\r\c"
mpifort -c ./src/LsystemClass/LsystemClass.f90 -o  ./inc/LsystemClass.o



# Compilation of Solvers
echo "Compiling ./src/DiffusionEquationClass/DiffusionEquationClass.f90" 
echo " >> DiffusionEquationClass.o "
echo " | ###############             | (70%)\r\c"
mpifort -c ./src/DiffusionEquationClass/DiffusionEquationClass.f90 -o  ./inc/DiffusionEquationClass.o
echo "Compiling ./src/FiniteDeformationClass/FiniteDeformationClass.f90" 
echo " >> FiniteDeformationClass.o "
echo " | ################            | (75%)\r\c"
mpifort -c ./src/FiniteDeformationClass/FiniteDeformationClass.f90 -o  ./inc/FiniteDeformationClass.o
echo "Compiling ./src/ContactMechanicsClass/ContactMechanicsClass.f90" 
echo " >> ContactMechanicsClass.o "
echo " | #################           | (80%)\r\c"
mpifort -c ./src/ContactMechanicsClass/ContactMechanicsClass.f90 -o  ./inc/ContactMechanicsClass.o
echo "Compiling ./src/MultiDiffDeformClass/MultiDiffDeformClass.f90" 
echo " >> MultiDiffDeformClass.o "
echo " | ####################        | (85%)\r\c"
mpifort -c ./src/MultiDiffDeformClass/MultiDiffDeformClass.f90 -o  ./inc/MultiDiffDeformClass.o
echo "Compiling ./src/MultiPhysicsClass/MultiPhysicsClass.f90" 
echo " >> MultiPhysicsClass.o "
echo " | ########################    | (90%)\r\c"
mpifort -c ./src/MultiPhysicsClass/MultiPhysicsClass.f90 -o  ./inc/MultiPhysicsClass.o
echo "Compiling ./src/SpaceTimeDeformClass/SpaceTimeDeformClass.f90" 
echo " >> SpaceTimeDeformClass.o "
echo " | ########################    | (92%)\r\c"
mpifort -c ./src/SpaceTimeDeformClass/SpaceTimeDeformClass.f90 -o  ./inc/SpaceTimeDeformClass.o


# Compilation of Fields 
echo "Compiling ./src/FieldClass/FieldClass.f90" 
echo " >> FieldClass.o"
echo " | ##########################  | (95%)\r\c"
mpifort -c ./src/FieldClass/FieldClass.f90 -o  ./inc/FieldClass.o
echo "Compiling ./src/SimulatorClass/SimulatorClass.f90" 
echo " >> SimulatorClass.o"
echo " | ########################## |  (98%)\r\c"
mpifort -c ./src/SimulatorClass/SimulatorClass.f90 -o  ./inc/SimulatorClass.o
echo "Compiling ./src/SiCroFClass/SiCroFClass.f90" 
echo " >> SiCroFClass.o"
echo " | ########################## |  (99%)\r\c"
mpifort -c ./src/SiCroFClass/SiCroFClass.f90 -o  ./inc/SiCroFClass.o
echo "Copying input files from INPUT/           " 
echo " >> *.txt, *.scf"
echo " | ########################### | (100%)\r"
cp ipynb/* .
echo "    "


echo " Total 22 objects are compiled  "
echo " SiCroF is successfully installed !!"
echo "    "
