# This Makefile does not work as it is. It needs revisions.

PlantFEM:./inc/obj.o ./src/PlantFEM/PlantFEM.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./inc/obj.o ./src/PlantFEM/PlantFEM.f90 -o  ./inc/PlantFEM.o

TimeClass:./src/TimeClass/TimeClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/TimeClass/TimeClass.f90 -o  ./inc/TimeClass.o


TermClass:./src/TermClass/TermClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/TermClass/TermClass.f90 -o  ./inc/TermClass.o


MathClass:./src/MathClass/MathClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/MathClass/MathClass.f90 -o  ./inc/MathClass.o


PhysicsClass:./src/PhysicsClass/PhysicsClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PhysicsClass/PhysicsClass.f90 -o  ./inc/PhysicsClass.o


HTTPClass:./src/HTTPClass/HTTPClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/HTTPClass/HTTPClass.f90 -o  ./inc/HTTPClass.o


IOClass:./src/IOClass/IOClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/IOClass/IOClass.f90 -o  ./inc/IOClass.o


KinematicClass:./src/KinematicClass/KinematicClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/KinematicClass/KinematicClass.f90 -o  ./inc/KinematicClass.o


RandomClass:./src/RandomClass/RandomClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/RandomClass/RandomClass.f90 -o  ./inc/RandomClass.o


ArrayClass:./src/ArrayClass/ArrayClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/ArrayClass/ArrayClass.f90 -o  ./inc/ArrayClass.o


VertexClass:./src/VertexClass/VertexClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/VertexClass/VertexClass.f90 -o  ./inc/VertexClass.o


GraphClass:./src/GraphClass/GraphClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/GraphClass/GraphClass.f90 -o  ./inc/GraphClass.o


VectorClass:./src/VectorClass/VectorClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/VectorClass/VectorClass.f90 -o  ./inc/Vector.o


EquationClass:./src/EquationClass/EquationClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/EquationClass/EquationClass.f90 -o  ./inc/Equation.o


MPIClass:./src/MPIClass/MPIClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/MPIClass/MPIClass.f90 -o  ./inc/MPIClass.o


DictionaryClass:./src/DictionaryClass/DictionaryClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/DictionaryClass/DictionaryClass.f90 -o  ./inc/DictionaryClass.o


OpenMPClass:./src/OpenMPClass/OpenMPClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/OpenMPClass/OpenMPClass.f90 -o  ./inc/OpenMPClass.o


LinearSolverClass:./src/LinearSolverClass/LinearSolverClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/LinearSolverClass/LinearSolverClass.f90 -o  ./inc/LinearSolverClass.o


GeometryClass:./src/GeometryClass/GeometryClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/GeometryClass/GeometryClass.f90 -o  ./inc/GeometryClass.o


RouteOptimizationClass:./src/RouteOptimizationClass/RouteOptimizationClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/RouteOptimizationClass/RouteOptimizationClass.f90 -o  ./inc/RouteOptimizationClass.o


TreeClass:./src/TreeClass/TreeClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/TreeClass/TreeClass.f90 -o  ./inc/TreeClass.o


CSVClass:./src/CSVClass/CSVClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/CSVClass/CSVClass.f90 -o  ./inc/CSVClass.o


ShapeFunctionClass:./src/ShapeFunctionClass/ShapeFunctionClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/ShapeFunctionClass/ShapeFunctionClass.f90 -o  ./inc/ShapeFunctionClass.o



STLClass:./src/STLClass/STLClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/STLClass/STLClass.f90 -o  ./inc/STLClass.o



WebServerClass:./src/WebserverClass/WebServerClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/WebserverClass/WebServerClass.f90 -o  ./inc/WebServerClass.o



PhysicalFieldClass:./src/PhysicalFieldClass/PhysicalFieldClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PhysicalFieldClass/PhysicalFieldClass.f90 -o  ./inc/PhysicalFieldClass.o



std:./src/std/std.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/std/std.f90 -o  ./inc/std.o




MeshClass:./src/MeshClass/MeshClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/MeshClass/MeshClass.f90 -o  ./inc/MeshClass.o


MaterialPropClass:./src/MaterialPropClass/MaterialPropClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/MaterialPropClass/MaterialPropClass.f90 -o  ./inc/MaterialPropClass.o


ControlParameterClass:./src/ControlParameterClass/ControlParameterClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/ControlParameterClass/ControlParameterClass.f90 -o  ./inc/ControlParameterClass.o


BoundaryConditionClass:./src/BoundaryConditionClass/BoundaryConditionClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/BoundaryConditionClass/BoundaryConditionClass.f90 -o  ./inc/BoundaryConditionClass.o


StrainClass:./src/StrainClass/StrainClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/StrainClass/StrainClass.f90 -o  ./inc/StrainClass.o


StressClass:./src/StressClass/StressClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/StressClass/StressClass.f90 -o  ./inc/StressClass.o


ConstitutiveModelClass:./src/ConstitutiveModelClass/ConstitutiveModelClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/ConstitutiveModelClass/ConstitutiveModelClass.f90 -o  ./inc/ConstitutiveModelClass.o
# Compilation of high-level classes


FEMDomainClass:./src/FEMDomainClass/FEMDomainClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  FEMDomainClass:./src/FEMDomainClass/FEMDomainClass.f90-c ./src/FEMDomainClass/	FEMDomainClass.f90 -o  ./inc/FEMDomainClass.o 


FEMIfaceClass:./src/FEMIfaceClass/FEMIfaceClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/FEMIfaceClass/FEMIfaceClass.f90 -o  ./inc/FEMIfaceClass.o


PostProcessingClass:./src/PostProcessingClass/PostProcessingClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PostProcessingClass/PostProcessingClass.f90 -o  ./inc/PostProcessingClass.o


PreProcessingClass:./src/PreProcessingClass/PreProcessingClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PreProcessingClass/PreProcessingClass.f90 -o  ./inc/PreProcessingClass.o


fem:./src/fem/fem.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/fem/fem.f90 -o  ./inc/fem.o




# Compilation of Solvers


DiffusionEquationClass:./src/DiffusionEquationClass/DiffusionEquationClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/DiffusionEquationClass/DiffusionEquationClass.f90 -o  ./inc/DiffusionEquationClass.o


FiniteDeformationClass:./src/FiniteDeformationClass/FiniteDeformationClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/FiniteDeformationClass/FiniteDeformationClass.f90 -o  ./inc/FiniteDeformationClass.o


ContactMechanicsClass:./src/ContactMechanicsClass/ContactMechanicsClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/ContactMechanicsClass/ContactMechanicsClass.f90 -o  ./inc/ContactMechanicsClass.o


MultiDiffDeformClass:./src/MultiDiffDeformClass/MultiDiffDeformClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/MultiDiffDeformClass/MultiDiffDeformClass.f90 -o  ./inc/MultiDiffDeformClass.o


MultiPhysicsClass:./src/MultiPhysicsClass/MultiPhysicsClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/MultiPhysicsClass/MultiPhysicsClass.f90 -o  ./inc/MultiPhysicsClass.o


SpaceTimeDeformClass:./src/SpaceTimeDeformClass/SpaceTimeDeformClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/SpaceTimeDeformClass/SpaceTimeDeformClass.f90 -o  ./inc/SpaceTimeDeformClass.o


PoromechanicsClass:./src/PoromechanicsClass/PoromechanicsClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PoromechanicsClass/PoromechanicsClass.f90 -o  ./inc/PoromechanicsClass.o


WaterAbsorptionClass:./src/WaterAbsorptionClass/WaterAbsorptionClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/WaterAbsorptionClass/WaterAbsorptionClass.f90 -o  ./inc/WaterAbsorptionClass.o
# Compilation of Fields 


FieldClass:./src/FieldClass/FieldClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/FieldClass/FieldClass.f90 -o  ./inc/FieldClass.o


SimulatorClass:./src/SimulatorClass/SimulatorClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/SimulatorClass/SimulatorClass.f90 -o  ./inc/SimulatorClass.o


SiCroFClass:./src/SiCroFClass/SiCroFClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/SiCroFClass/SiCroFClass.f90 -o  ./inc/SiCroFClass.o


sim:./src/sim/sim.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/sim/sim.f90 -o  ./inc/sim.o



# Compilation of agricultural objects


RidgeClass:./src/RidgeClass/RidgeClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/RidgeClass/RidgeClass.f90 -o  ./inc/RidgeClass.o


AirClass:./src/AirClass/AirClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/AirClass/AirClass.f90 -o  ./inc/AirClass.o


DamClass:./src/DamClass/DamClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/DamClass/DamClass.f90 -o  ./inc/DamClass.o


LightClass:./src/LightClass/LightClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/LightClass/LightClass.f90 -o  ./inc/DamClass.o



FertilizerClass:./src/FertilizerClass/FertilizerClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/FertilizerClass/FertilizerClass.f90 -o  ./inc/FertilizerClass.o




StemClass:./src/StemClass/StemClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/StemClass/StemClass.f90 -o  ./inc/StemClass.o


PlantRootClass:./src/PlantRootClass/PlantRootClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PlantRootClass/PlantRootClass.f90 -o  ./inc/PlantRootClass.o



RootClass:./src/RootClass/RootClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/RootClass/RootClass.f90 -o  ./inc/RootClass.o



PetiClass:./src/PetiClass/PetiClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PetiClass/PetiClass.f90 -o  ./inc/PetiClass.o


PodClass:./src/PodClass/PodClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PodClass/PodClass.f90 -o  ./inc/PodClass.o


FlowerClass:./src/FlowerClass/FlowerClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/FlowerClass/FlowerClass.f90 -o  ./inc/FlowerClass.o


PanicleClass:./src/PanicleClass/PanicleClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PanicleClass/PanicleClass.f90 -o  ./inc/PanicleClass.o


LeafClass:./src/LeafClass/LeafClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/LeafClass/LeafClass.f90 -o  ./inc/LeafClass.o



PlantNodeClass:./src/PlantNodeClass/PlantNodeClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/PlantNodeClass/PlantNodeClass.f90 -o  ./inc/PlantNodeClass.o



InsectClass:./src/InsectClass/InsectClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/InsectClass/InsectClass.f90 -o  ./inc/InsectClass.o



LsystemClass:./src/LsystemClass/LsystemClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/LsystemClass/LsystemClass.f90 -o  ./inc/LsystemClass.o


SeedClass:./src/SeedClass/SeedClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/SeedClass/SeedClass.f90 -o  ./inc/SeedClass.o


SoilClass:./src/SoilClass/SoilClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/SoilClass/SoilClass.f90 -o  ./inc/SoilClass.o



SoybeanClass:./src/SoybeanClass/SoybeanClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/SoybeanClass/SoybeanClass.f90 -o  ./inc/SoybeanClass.o



RiceClass:./src/RiceClass/RiceClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/RiceClass/RiceClass.f90 -o  ./inc/RiceClass.o



FarmClass:./src/FarmClass/FarmClass.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/FarmClass/FarmClass.f90 -o  ./inc/FarmClass.o


obj:./src/obj/obj.f90
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -c ./src/obj/obj.f90 -o  ./inc/obj.o

inc:obj.so ./inc/*.
	mpif90 -fopenmp -fopenacc -shared -fPIC -g -fcheck=all -fintrinsic-modules-path inc/  -o obj.so ./inc/*.o 


