#!/bin/sh

brew install  gcc
brew install  openmpi
brew install  python3
brew install  gmsh
brew install  gnuplot
brew install curl
curl https://bootstrap.pypa.io/get-pip.py -o ~/get-pip.py
sudo python3 ~/get-pip.py
sudo pip install pillow
sudo pip install numpy
sudo pip install scipy
sudo pip install matplotlib
sudo pip install jupyter
