module std
    use, intrinsic :: iso_fortran_env
    use uuid_module
    use PhysicalConstantsClass
    use BitClass
    use StringClass
    use TimeClass
    use TermClass
    use MathClass
    use ConsoleClass
    use PhysicsClass
    use HTTPClass
    use IOClass
    use HTMLClass
    use KinematicClass
    use RandomClass
    use ArrayClass
    use PCAClass
    use SDEClass
    use VertexClass
    use GraphClass
    use CSVClass
    use VectorClass
    use EquationClass
    use MPIClass
    use DictionaryClass
    use OpenMPClass
    use LTISystemClass
    use GAClass
    use LinearSolverClass
    use GeometryClass
    use TreeClass
    use ShapeFunctionClass
    use RouteOptimization
    use STLClass
    use WebserverClass
    use PhysicalFieldClass
    implicit none

end module std